POST http://localhost:3333/videos
Content-Type: application/json

{   
    
    "title": "Video node",
    "description": "Este é o Video node",
    "duration": 180
}


###
GET http://localhost:3333/videos
Content-Type: application/json


###

GET http://localhost:3333/videos?search=node
Content-Type: application/json



###

PUT http://localhost:3333/videos/b23eee0c-7261-4475-8ef1-60cfd1f088d8
Content-Type: application/json

{

    "title": "Video node 02",
    "description": "Este é o Video node 02",
    "duration": 190

}

###

DELETE http://localhost:3333/videos/23eee0c-7261-4475-8ef1-60cfd1f088d8
